### ISSUE TITLE
Move the start / stop logic of the ThreadUtils of the LS PR's to a class extending the Executor interface.

### ISSUE THREAD

**Issue by hmoog** [iotaledger/iri#1061]
To adhere to correct OO principles, we change the start and stop logic from a global shared util class to a instance based executor-like service.

**Comment by GalRogozinski** [comment]
When you get to this issue it will be best to have your Jobs implement Runnable (can also be Callable but in your case Runnable).

The reason is that while reviewing I wanted to comment on why in the `process()` method you update an `int` and not an `AtomicInteger`. Then I realized that only one thread will run the Job by design.

Implementing the correct interfaces will make this clear.
