### ISSUE TITLE
Test the LOCAL_SNAPSHOTS_DEPTH flag

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1167]
### Description
General tests for the LOCAL_SNAPSHOTS_DEPTH flag. 

1. Test various numbers: For example, 1, 10, 50, 500. Play around with that.
2. Test negative numbers.
3. You actually keep DEPTH amount of milestone post-snapshot.
4. What happens if INTERVAL is >= than DEPTH?
5. Verify that snapshotting actually keeps DEPTH milestones after snapshot: if you snapshotted at 42, latest milestone should be 42+DEPTH.
6. How do we handle when the coo references something > LOCAL_SNAPSHOT_DEPTH? Try what happens here? Same with DELAY, where it should always end in horrors. 
7. Change up the DEPTH settings (up, down) and keep the same database.

**Comment by DyrellC** [comment]
### Results 
**_1. Test various numbers: For example, 1, 10, 50, 500. Play around with that._**

Various depths were tried. The minimum of depth 50 is enforced correctly. There were no problems with different depths between connected nodes. The size of the db's did not vary much with the default pruning delay set so high. 

**_2. Test negative numbers._**

Same as above, the minimum depth cannot be less than 50. 

**_3. You actually keep DEPTH amount of milestone post-snapshot._**

There were always at least DEPTH amount of milestones present after the snapshot. This was tested at multiple depths. 


**_4. What happens if INTERVAL is >= than DEPTH?_**

The node continues to operate as intended, but the available milestones will vary depending on what transactions have already been pruned due to the depth. The snapshot will be taken at the next interval and begin pruning at the DEPTH + DELAY.

**_5. Verify that snapshotting actually keeps DEPTH milestones after snapshot: if you snapshotted at 42, latest milestone should be 42+DEPTH._**

The latest milestone in each db was the snapshot + DEPTH + PRUNING for each depth, but the present milestones would become inconsistent before the depth in most cases. These tails would cause an inconsistent ledger state if referenced by a transaction. In most cases, the latest consistent milestone kept was ~25 milestones back at DEPTH=50.  


**_6. How do we handle when the coo references something > LOCAL_SNAPSHOT_DEPTH? Try what happens here? Same with DELAY, where it should always end in horrors._**

If the coo references a transaction that is below the Depth, but above the delay, the milestone will still become solidified. If the referenced transaction is below the pruning delay though, the milestone will not solidify because the transaction tail will not be present in the db. 


**_7. Change up the DEPTH settings (up, down) and keep the same database._**

The node adjusts itself for the next snapshot with the available milestones left in the db. If the depth is lowered then it will begin pruning at that new depth during the next snapshot, if the depth is higher it will not prune until enough milestones are present in the db to be over the depth, and once it has reached this point, it will begin pruning after the next scheduled snapshot. 


**_Note:_** _There were 2 instances that I was able to break synchronisation but both required me to interrupt the milestone issuance in some manner:_

The first case, the node was restarted while milestones continued to be issued. When those missing milestones were sent to the node manually, the node recovered the rest of the milestones up to the current state, but after that, the entry points generated did not work and the node was never able to recover. My theory is that the local snapshot taken once the node went out of sync generated entry points that were not consistent with the db once the missing milestones were referenced back into the db. No new milestones could be issued at this point so no new snapshot was taken to replace the corrupted entry points. 

The second instance was essentially the reverse. I stopped the milestones from issuing and started it up again skipping one of the milestones along the way. When that milestone was issued the recovery process never began and the node remained unsynced as the new milestones were being generated. My theory is that the missing milestone, once issued, referenced one of the newly inconsistent "future" milestones and so the node was never able to solidify that particular milestone, and the recovery process never had a chance to start. 

Both of these instances have been hard to repeat and both seem particularly niche scenarios that I'm not sure would occur in a real world scenario, but regardless I wanted us to be aware that they happened.
