### ISSUE TITLE
Investigate out of memory issues

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1291]
### Description
We're getting java OOM errors on 1.6.0 and we need to investigate what's killing them. 

One culprit is that we're not able to find the solid entry points and we're exhausting the resources on this. @DyrellC 

#1273

**Comment by GalRogozinski** [comment]
Another OOM seemed to occur during `MilestonePrunerJob#getElementsToDelete` while traversing the tangle with `DagHelper`.

**Comment by DyrellC** [comment]
After thorough investigation it has been determined that the primary sources of memory leaks in the 1.6.0 release were the `spentAddresses` db handling and the `asyncTransactionPruner`. In both cases, very large queues of transactions needed to undergo processing, and the storing of all these values in these queues, as well as the serialisation required before writing to file would lead to high old gen heap consumption until the node would run out of available memory and crash. 

The `spentAddresses` memory leak has been resolved by changing the process to write to a db instead of a file, and instead of processing all of the potentially spent addresses at once, they are checked during ledger validation instead, so that there is no more need for large lists and queues. This led to a significant drop in memory usage following local snapshots, and has also led to a reduction in cpu usage. 

The `asyncTransactionPruner` memory leak requires further discussion, but a meantime patch of disabling the writing of pruner jobs to the `mainnet.snapshot.gc` file will remove the problem and stabilise the nodes while they are running. The problem with this approach is that currently this method is how a node stores it's currently processing jobs in the event the node is shut down, and needs to restart. If this feature is disabled, the pruner jobs that were not completed prior to the shutdown will not be persisted, and the node will not pick up those jobs anymore. Possible solutions to this problem have already been discussed, including persisting the jobs in a db, or having a new pruner job scanning process that can look for these abandoned jobs to pick them back up again. There are pro's and con's to each of the proposed solutions and further discussions will need to be had before a choice is made, but for the 1.6.1 release, the removal of the writing feature will reduce memory usage and cpu usage dramatically as well.

**Comment by jakubcech** [comment]
Thanks, we have one more thing we'd like to test with a sidetangle here. Gal will have more context here.
