### ISSUE TITLE
Save local snapshot data in the database 

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1317]
### Description
Local snapshot files shouldn't be stored as files, but in a database instead. This will give us the benefit of compression (among other things). Then we can think about other optimizations. 

### Requirements
- [ ] New column families for the snapshot.state and snapshot.metadata 1:1 with the current files
- [ ] We have providers that point to the files and they should point to the DB instead

**Comment by muXxer** [comment]
Pleeeeease leave an option to export the local snapshot in the same file format like right now, or provide a binary format which is specified. Otherwise I can't import it in Hercules :(

**Comment by GalRogozinski** [comment]
Using https://github.com/iotaledger/Snapshot.ixi can help you maybe?

**Comment by DyrellC** [comment]
Writing to a state file instead of storing in the db is responsible for several oom errors on my end. 

![image](https://user-images.githubusercontent.com/34013004/52445159-9230e280-2ae7-11e9-9a72-ab45acfea8ef.png)

At https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/transactionpruning/async/AsyncTransactionPruner.java#L329, the pruner writes the state to a file, and this consumes large amounts of memory until eventually the node crashes. Each time the `SnapshotServiceImpl` takes a snapshot, a long list of additional jobs are added to the `jobQueue`, and the pruner can't process through all of them fast enough, so the set that needs to be streamed continues to grow and grow.

Eventually the retained size exceeds the available space and the node will crash. 
![image](https://user-images.githubusercontent.com/34013004/52446307-d8d40c00-2aea-11e9-8502-6cbfe2107f7a.png)

**Comment by GalRogozinski** [comment]
Fixed by #1584
