### ISSUE TITLE
Find out when .sst files are actually created in the spent-addresses-db folder

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iri#1429]
### Bug description
It's currently not clear when `.sst` files are persisted in the `spent-addresses-db` folder. IRI uses the default options for RocksDB which given certain thresholds  flushes the memtable to .sst files. https://github.com/facebook/rocksdb/wiki/MemTable#Flush

We should have a clear picture of how the parameters in RocksDB effect the flushing of the in memory data to be capable of answering questions like: "When is the in memory actually persisted on disk?"

This issue was raised because a node in the ICC network which is supposed to serve backups of the local snapshot files, does not generate the .sst files. This, even after pruning delays are hit and the network has constantly at least one value transfer between milestones. 

### IRI version
The IRI ICC docker image 0.1.14

### Expected behaviour
.sst files are persisted in a reasonable interval.

### Actual behaviour
.sst files are not persisted over a longer period of time even if pruning delays happend

**Comment by luca-moser** [comment]
So it either creates .sst files when (IRI uses default RocksDB parameters/options):
- `write_buffer_size` is exceeded, which per default is 64 megabytes
- `max_total_wal_size` is exceeded which is made up of `[sum of all write_buffer_size * max_write_buffer_number] * 4` which should translate to at least 256 megabytes, I guess
- `db_write_buffer_size` is exceeded but is 0 per default which means it's actually disabled

I assume what's happening on the ICC network regarding the `.sst` files, is that the memtable just never reached 64 megabytes yet, therefore not flushing the memtable. And because I am unable to start with the same `spent-addresses-db` because IRI complains about not finding `.sst` files in there, the WAL file was fresh up on each node restart (because I deleted the entire folder), making it so that I've never reached the 64 megabytes of needed data in the memtables to trigger a flush. (edited)

**Comment by GalRogozinski** [comment]
@luca-moser and @kwek20 
Maybe we can use this feature instead of the cache somehow?

What I mean is that we usually do the RW on newer transactions. If we have a big enough memtable then it is possible that it can fit all of the transactions we walk on and thus we can avoid disk I/O.

In your tests did you conclude that even data that is not flushed is significantly slower than a hashmap? It sounds reasonable that due to JNI overhead this will be the case. I just remember that in our meetings we said the bottleneck is I/O.

I just want to make sure that before we add caching code (which might be a little hard) we exhaust all other options.

**Comment by kwek20** [comment]
We can use this test as a guideline: https://github.com/facebook/rocksdb/wiki/RocksJava-Performance-on-Flash-Storage; meaning rocksdb supports at least 84mb/s passthrough.

I think we should keep a node of max 4gb ram in mind, and by that set a limit of what we can change on rocksdb memtables(Which whould be sufficient, but means we cant go over like 2gb as theres other claims on memory)

Luca did test with a cache for like 1gb size(just guessing a number, high) and saw no improvements

**Comment by GalRogozinski** [comment]
If I look at random tests on the internet I can find results that look worse for hashmap (http://vanillajava.blogspot.com/2011/07/low-gc-in-java-using-primitives.html) even though it doesn't make sense that it will be worse than RocksDb.

Anyhows, my point is that I explicitly remember @luca-moser using the word "I/O". Since he claimed increasing the cache didn't do anything I am guessing that either:
1. He didn't witness any I/O at all in his test
2. He witnessed I/O but the cache didn't do anything to decrease it

I haven't seen the code of the test but option 2 is possible because of a confusion between `memtable` and `block cache`. IIUC a `block cache` only gets populated after a read. If he just increased the `block cache` but only read once each value then there shouldn't be any less I/O I believe. 

I have no idea if the above is what happened but if it did it probably stemmed from the bad title of #1630. I wouldn't be surprised if option (1) is also the case.

*I am insisting of understanding it better because:*
1. Maybe there is an easy configuration change we can do to improve performance
2. If we implement our own caching that will replace `block cache` we need to understand:
    * How much faster it is then just using `memtable` w/o I/O
    * What should be the size ratio of cache/`memtable`

**Comment by kwek20** [comment]
Also, according to this page https://github.com/facebook/rocksdb/wiki/Managing-Disk-Space-Utilization#limiting-the-db-size

"Every time a new SST file is created, either by flush or compaction,"

So we should also look into when compaction happens

**Comment by kwek20** [comment]
@GalRogozinski 
I guess im doing this ticket now :P
It matters for the database size, which only gets updated when the sst files get updated

**Comment by luca-moser** [comment]
> MemTable is an in-memory data-structure holding data before they are flushed to SST files. It serves both read and write - new writes always insert data to memtable, and reads has to query memtable before reading from SST files, because data in memtable is newer. Once a memtable is full, it becomes immutable and replace by a new memtable. A background thread will flush the content of the memtable into a SST file, after which the memtable can be destroyed.

> Block cache is where RocksDB caches data in memory for reads. User can pass in a Cache object to a RocksDB instance with a desired capacity (size). A Cache object can be shared by multiple RocksDB instances in the same process, allowing users to control the overall cache capacity. The block cache stores uncompressed blocks. Optionally user can set a second block cache storing compressed blocks. Reads will fetch data blocks first from uncompressed block cache, then compressed block cache. The compressed block cache can be a replacement of OS page cache, if Direct-IO is used.

> IIUC a block cache only gets populated after a read.

Increasing the block cache should have the same effect as increasing the memtable. In IRI this should be the case, as it should load read transactions into the LRU cache and then be available for subsequent calls as it shouldn't evict elements on a 1GB capacity cache (within milliseconds of having requested the element).

---

The block caches for both compress and uncompressed were set to 1GB:
```java
cache = new LRUCache(1 * SizeUnit.GB, 2);
compressedCache = new LRUCache(1 * SizeUnit.GB, 10);

BlockBasedTableConfig blockBasedTableConfig = new BlockBasedTableConfig().setFilterPolicy(bloomFilter);
blockBasedTableConfig
    .setFilterPolicy(bloomFilter)
    .setBlockSizeDeviation(10)
    .setBlockRestartInterval(16)
    .setBlockCache(cache)
    .setBlockCacheCompressed(compressedCache);
```

I think you can take Brord's newest changes which integrate RocksDB 6.x and increase the block cache or memtable there and retest if you see any performance gains.

My feeling is that constructing the `TransactionViewModel/Transaction` object might just take too much time, so that caching the underlying bytes is only one part of the solution (but I didn't profile that, so it's just an idea).

> Anyhows, my point is that I explicitly remember @luca-moser using the word "I/O". Since he claimed increasing the cache didn't do anything I am guessing that either:

Of course with "I/O" I meant hitting the database (whether it does actual I/O or just reads stuff from the cache doesn't matter in this context). As mentioned before, the slowest operation in tip-selection is RocksDB's `get()` method. We have several YourKit profiling files showing this which are available on Slack.

> I am insisting of understanding it better because:
> Maybe there is an easy configuration change we can do to improve performance

IRI must rewrite its persistence story even if using the RocksDB cache solves the performance bottleneck, as it is riddled with race condition bugs otherwise, as multiple threads handle separate instances of entities

**Comment by GalRogozinski** [comment]
> Increasing the block cache should have the same effect as increasing the memtable. In IRI this should be the case, as it should load read transactions into the LRU cache and then be available for subsequent calls as it shouldn't evict elements on a 1GB capacity cache

I still think that it only start helping on the second read.

> I think you can take Brord's newest changes which integrate RocksDB 6.x and increase the block cache or memtable there and retest if you see any performance gains.

We started running our DB benchmark as a buildkite benchmark. I need to do #1651 and DevOps need to clean up some stuff. But we shall indeed start running those tests in a transparent manner.

> My feeling is that constructing the TransactionViewModel/Transaction object might just take too much time, so that caching the underlying bytes is only one part of the solution (but I didn't profile that, so it's just an idea).

It is probably more the JNI overhead than the actual construction of the object (didn't profile either). This of course, doesn't affect your conclusion.

> Of course with "I/O" I meant hitting the database (whether it does actual I/O or just reads stuff from the cache doesn't matter in this context).

Thanks for the clarification :-)

> IRI must rewrite its persistence story even if using the RocksDB cache solves the performance bottleneck, as it is riddled with race condition bugs otherwise, as multiple threads handle separate instances of entities

Yes, we have #926 that would make the persistence layer be rewritten in a safer manner. Correct caching will also remove race conditions since 2 different reads won't be creating 2 java objects that resemble the data model (i.e. a Transaction)

**Comment by kwek20** [comment]
Issue no longer relevant as this db doesnt exist anymore. Also The info above gives a pretty decent sum of how to get sst files. @GalRogozinski Lets close it
