### ISSUE TITLE
Create a tool that merges IRI DBs

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1473]
### Description
Tool that merges individual IRI DBs, so you can take DBs from different sources, with data from different periods of time and build a single DB with all the history.

### Motivation
Ability to build a DB from different sources. For example, for 'permanode' scenarios. 

### Requirements
- [ ] I run a tool that takes multiple DBs
- [ ] The tool produces a compatible DB with data from all the DBs

### Open questions
- How does this work when: 
     a) we have overlapping DBs
     b) we have DBs covering different epochs

### Technical bits

There are two approaches that I think we can use. The second one is probably too complicated and not completely exposed. The first one would be great if it worked as it could be a cheap way of achieving the merge:
1. repairDB() which drops the Manifest and rebuilds it with the files that are in the folder. The flow then is 
    - Copy .sst files into the DB
    - Call repairDB() (https://github.com/facebook/rocksdb/wiki/RocksDB-Repairer)
2. mergeDBs() - there's a merge operator describe here: https://github.com/facebook/rocksdb/wiki/Merge-Operator - Haven't explored this too much. Someone was also referencing mergeDatabases() in one of the GitHub issues I found on this, but I haven't seen that exposed in rocksDB, neither documented.

**Comment by DyrellC** [comment]
Regarding approach #1: 
I attempted various combinations of combined `.sst` `.log`, `CURRENT`, and `OPTIONS` files to create the repaired database. Unfortunately none of these yielded a usable database. Many transactions and files get "lost" in the repair process and the db is never put back together the way it should be. Even when only removing the MANIFEST from a single db and repairing, the db becomes unusable with IRI. As discussed with Gal, this will not be a viable approach. 

Regarding approach #2: 
This methodology doesn't serve the purposes of the goal that's laid out for this issue. The merge operation is intended for appending data in a single database, and doesn't work for combining several sources together in any tangible way. 

Another approach: 
I've been looking at putting together a more manual process that works more from a node operations level, which iteratively works through each provided db, checks for collisions and re-validates transactions into one larger db. In order to do this a snapshot state from the earliest db genesis point is necessary, and the tool would start a new db with this snapshot as a starting point. It then iterates through each column family (starting with transaction objects), validates the consistency of the transactions with the ledger state (raising flags for any collisions that would cause a discrepancy), and stores them in the new db. This process will take some time compared to doing a `repairDb` or `merge` operator, but seeing as these two processes haven't yielded any usable db's yet, I believe it's the most likely alternative for a working merge tool.

**Comment by GalRogozinski** [comment]
> raising flags for any collisions that would cause a discrepancy
how exactly are you checking that

Can you also describe for which column families you "write" to and for which you "merge" to
