### ISSUE TITLE
Benchmark uniform random tipselection performance

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1568]
### Description
We want to benchmark fully random tip selection to set some good baseline to reflect upon. 

Reuse JMeter tests. https://github.com/iotaledger/iri-regression-tests/tree/master/Nightly-Tests/Jmeter-Tests
We should also use the profiler. 

### Motivation
Have a [naive] baseline for tipsel improvements. 

### Requirements
- Change the IRI on which the benchmark runs so that `TipsViewmodel` picks something like totally random. Only return solid tips, no need to worry about the path that returns non-solid if there are no solid tips.
- Have a node that uses an existing DB in our S3 bucket. Note it down in the comment here so that we can always perform the same test. This will allow us to redo the test later on whenever. 
- Use an isolated machine, make sure you use the same for #1567 
- Run both the Jmeter tests (can be run manually). https://github.com/iotaledger/iri-regression-tests/tree/master/Nightly-Tests/Jmeter-Tests
- Run the yourkit profiler.
- Give us results and write a beautiful summary.

**Comment by DyrellC** [comment]
###Test setup
*DB: * https://dbfiles.iota.org/mainnet/1.7.0/db-1072888.tar
*VM: * 8GB RAM, 160GB HDD, Ubuntu16.04.4x64

*_At Rest/Pre Test Operational Requirements_*
*CPU: * ~3%
*Mem: * ~780MB

**Comment by DyrellC** [comment]
_Test run using 1000 threads looping 1 time with gtta calls_

### Standard Performance
![image](https://user-images.githubusercontent.com/34013004/63555801-9a8ac100-c4ff-11e9-8267-21cc45eaa505.png)

**API response speed:** In order to return all 1000 calls, the node takes ~279 seconds. 
**Memory usage:**  Memory usage goes from ~780MB to 1GB within the first 200 response cycles.
**CPU usage:** Averages around ~30% during processing. 

### With TipsViewModel Change
![image](https://user-images.githubusercontent.com/34013004/63555882-f0f7ff80-c4ff-11e9-896b-72286e84af4a.png)

**API response speed:** In order to return all 1000 calls, the node takes ~232 seconds, a notable reduction of 40 seconds from the standard performance 
**Memory usage:**  Memory usage is very similar in that it reaches 1GB within the same timeframe. Negligible difference. 
**CPU usage:** Averages around ~25% during processing, slightly less than standard.

**Comment by DyrellC** [comment]
## _Test run using 1 thread looping 1000 times with gtta calls_
### Standard Performance
![image](https://user-images.githubusercontent.com/34013004/63555936-1be25380-c500-11e9-86b1-a08273a798cd.png)

**API response speed:** Averages half a second per response when sequentially sent
**Memory usage:** Memory usage continued to climb from ~780MB to 1GB over the span of the test, and did not drop after completion
**CPU usage:** Usage hovered at ~23-25% on average, less than with the 1000 calls at once due to the need to only process one request at a time. 

### With TipsViewModel Change
![image](https://user-images.githubusercontent.com/34013004/63555989-3f0d0300-c500-11e9-90c7-a4d30c29aab8.png)
**API response speed:** Marginal improvement for single calls. Response time reduced by ~50ms per call. 
**Memory usage:** Memory usage climbs slowly from ~780MB to 1GB over the span of the test. Takes much longer to increase the memory above 950MB than the standard performance. 
**CPU usage:** Usage hovered at ~15% on average, much less than the standard performance (~40% reduction)

**Comment by DyrellC** [comment]
### Notes
It appears that the URTS approach does provide a noticeable difference in response return time, but does not appear to make a significant difference with respect to CPU and Memory during batch calls. Sequential calls show that the URTS approach improves CPU performance during calls, but somewhere along the line this is lost when processing multiple requests at a time. In both the batch and single call scenarios memory does not appear to be affected.

**Comment by GalRogozinski** [comment]
Can I see the code of your branch?
It is weird that cpu and memory don't go down

**Comment by GalRogozinski** [comment]
@DyrellC , still waiting for the link to the branch :-)

**Comment by DyrellC** [comment]
Sorry @galrogo  I realised that changing the TVM doesn't actually have any effect on the gtta functionality as they don't actually interact with one another at all. I made a new branch with different modifications to remove the rating and weight calculations and output a proper uniform random selection. Performance was much better and showed the expected reduction in cpu and memory usage in comparison to the current usage. 

Branch: https://github.com/DyrellC/iri/tree/uniform-random-tipviewmodel

### 1000 Threads Looping 1 Time 
![image](https://user-images.githubusercontent.com/34013004/64391772-3855b400-d007-11e9-88c8-493cfb5abb52.png)


### 1 Thread Looping 1000 Times 
![image](https://user-images.githubusercontent.com/34013004/64391805-54f1ec00-d007-11e9-8e65-7fc0bda05f5d.png)

As you can see, the cpu usage is much less than standard, and the memory usage is negligible in comparison. Instead of spiking over 1GB, it stays almost the same. The same holds true when throwing 10000 calls at the node as well.
