### ISSUE TITLE
URW splitting test

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1592]
### Description
We want to try different attacks on nodes using URW on a private network before we perform tests on ICC/Mirrornet/Devnet. 

This test can make use of the splitting attack tool. Needs to be modified as it's set up for Spamnet. 
https://github.com/iotaledger/tangle-tools/tree/master/splitting-attack

### Motivation
1. Evaluate the safety of URW against known attacks. 
2. Compare behavior to the current approach. 

### Requirements
- [ ] Set up a private network with 1 node and Compass (e.g., with TIAB)
- [ ] Splitting attack using the Splitting attack tool (https://github.com/iotaledger/tangle-tools/tree/master/splitting-attack) - might need some changes as its written for spamnet
       - 2 spammers - 1 creates a subtangle, another creates honest transactions. 
       - We need adjust/play around with the TPS of the different spammers. Start with 1:1 and adjust with PoW, or you can use Luca's ZMQ spammer. 
       - Emit transaction, get the hash, censor the transaction.
       - Turn off the subtangle spammer and the subtangle should die off. 
       - In 5+ ticks, the transaction still isn't confirmed. 
- [ ] Post the results for each attack (on Confluence), compare to the current implementation of IRI. We can use the Splitting page on Confluence for a motivation on results summary. 
- [ ] Perform the same tests on an unchanged version IRI for comparison as well. Same conditions, DB, machine, TPS, calls, moon phase.

**Comment by kwek20** [comment]
After many splitsy splits; i came to the conclusion that this still happens when A=0 exactly equal to A!=0.
I have tried various splits: 2 way split, 3 way split, and many splits. As expected, one split is picked and the others abandoned. No change in behaviour from before a0.

Any spam used in some of the tests use tps: ~5 dtlg
![Screenshot (10)](https://user-images.githubusercontent.com/1417565/65619203-0b6e3e80-dfc0-11e9-8e06-bd5dc1a4f7cf.png)
![Screenshot (12)](https://user-images.githubusercontent.com/1417565/65619268-2345c280-dfc0-11e9-897d-daa50e1f90e4.png)

Numbers indicating confirmation percentage, which is going up again as soon as split attack stops, as expected
![Screenshot (13)](https://user-images.githubusercontent.com/1417565/65619282-29d43a00-dfc0-11e9-91c4-a7791aa2731e.png)

**Comment by jakubcech** [comment]
Thanks for the summary! :)
