### ISSUE TITLE
Allow users to manually tweak RocksDb Options

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1624]
### Description
Inside `mainnetdb` folder there is an Options file. It has all rocksdb configurations. Currently every time one restarts IRI, its contents is being replaced by hard coded options.
We want to ignore the hardcoded options in case the Options file is present.

### Motivation
One would like to tune RocksDb performance without changing java code.
Anyone in the community could fine settings that are good for him.

### Requirements
1. If options file is missing use hardcoded options
2. Else use options in file

**Comment by kwek20** [comment]
After investigating the creation of these files, I came to the conclusion that they cannot be deleted. There are always 2 OPTIONS-000XXX files. The previous configuration(lower number) and the current one(higher number). In our old code, we overwrote the options every time, so any change made to them would be discarded. I have now changed it so that you can modify the higher OPTIONS file. Attempting to change anything to the lower one will just be discarded. Now we have 3 options:
1. Only allow changing of the higher OPTIONS file, and don't have a custom config file elsewhere with just the options you want to change. This has the + of only being able to be changed on 1 spot, preventing confusion of which file to edit. It will remove the option to keep 1 config for both spent and mainnetdb
2. Have a custom config which we load if exists, discarding any possible changes made to the real OPTIONS file. Could cause said file modification confusions but can be used for both databases
3. Wait or make a PR so hat RocksJava supports merging 2 option files (Which it does in C), but this will take time

In my opinion, that lone hero who dares to play with these configurations will be experienced enough to not make the mistake of confusing files. (This is likely going to be only me anyways :sweat_smile: ). Waiting for a PR could take a long time, and writing it seems too much trouble for such feature. As you can now still modify options specific per DB using the higher OPTIONS file, I think we should take option 2.

Keep in mind that due to the fact that we make some hardcoded options changes (Like preferring command line log file location instead of options file), the options file number ALWAYS increases during a restart

**Comment by GalRogozinski** [comment]
@kwek20 you didn't make a final update on the issue. You put 3 options but you never clearly stated in a comment what needs to be done.

I am reopening this issue so you won't forget to place the comment.

**Comment by kwek20** [comment]
We chose option nr. 2. Instructions on usage can be found in the PR: https://github.com/iotaledger/iri/pull/1638
