### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by EasonWang01** [iotaledger/iri#357]
As IOTA is for IOT,can it running on a ARM architecture base embeded board now?
And why IOTA is focus on IOT but it using JAVA base not using c,c++ or Rust for better performance and less compile time?

**Comment by GhostTyper** [comment]
It is just fine to choose a wide spread language like Java to build the reference implementation. The node is not supposed to run on an IOT device. However the libraries are available in more languages.

**Comment by rotilho** [comment]
I'm not part of the develop group but I'll try to answer it.

I haven't tried to run IRI in ARM but JVM does support it as you can see here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Regarding the choice of a Java instead of other compiled alternatives: I think it completely make sense because of following 5 reasons

1. You can find everything for Java, from simple utils lib to powerful frameworks
2. Massive community of developers (specially server-side developers)
3. Java is verbose so easy to understand (not much magic happening)
4. Performance similar or better than compiled alternatives because of JIT
5. JVM

I'm almost confident that the intention is not run IRI in a low power embedded device but use a lib to access a external powerful node.

**Comment by Nolaan** [comment]
I find this very worrying. IoT! Most of those devices will run with low level/small footprint languages. Therefore excluding java. Sorry to let you know that C/C++ are kings in this field. There is also no shortage of libs and dev here too. So I'm still waiting for a solid answer. Since one of the core assumption was to run an efficient blockchain.

**Comment by th0br0** [comment]
IRI is only the initial reference implementation and we're not focused on sticking to Java. In fact, we're in the process of moving some of the core functionality to C/C++ at the moment. As part of this, ARM support will come. There has been work to make IRI run on an RPi before which I believe was successful. However, I do not have a link to this community developer's github account right now.

Depending on how small your device is, you'll probably want to run a light/thin client on your IoT device anyway and not a full node.

**Comment by EasonWang01** [comment]
Thank for response.I agree about it.

**Comment by jserv** [comment]
#312 is discussing about packaging for Arm architecture.
[Cavium ThunderX](https://www.cavium.com/ThunderX_ARM_Processors.html) is known to work, and you can even enable ARMv8-A virtualization to host several IRI instances: [Build Cloud Infrastructure with ARMv8](https://schd.ws/hosted_files/ossna2017/01/Build-Cloud-Infrastructure-with-ARMv8.pdf) (Page 26-28).

**Comment by Nolaan** [comment]
This is cloud! Servers! Not IOT!!!

**Comment by Nolaan** [comment]
Do you really think a weather station or smart meter will run on a 48core hardware?

**Comment by jserv** [comment]
@Nolaan, Not only Cavium ThunderX runs well but also [ASUS Tinker Board](https://www.asus.com/us/Single-Board-Computer/Tinker-Board/) is known to work.

ASUS Tinker Board is powered by quad-core ARM Cortex-A17-based processor, featuring 2GB of LPDDR3 dual-channel memory and equipped with an SD 3.0 interface that offers faster read and write speeds to expandable microSD cards used for GNU/Linux. @yillkid already runs IRI 1.4.x on ASUS Tinker Board for a while.
