### ISSUE TITLE
Slack link broken/expired

### ISSUE THREAD

**Issue by rafaelbrizola** [iotaledger/iri#383]
The link to the Iota slack channel in the README seems to be incorrect. It redirects to a page and when you click in "Join slack" you are redirected to another page with the message "This invite link is no longer active."

**Comment by devender-yadav** [comment]
https://join.slack.com/t/iotatangle/shared_invite/enQtMjgxNDY0Nzk4MjEwLTIyNzU0Nzc5YTA0MzFhZTAwNzkyZjc5ZjRhYmMxMGRlNjdiZGVmYTI4ZTcxMDhjNTQ1YjNkMTBiMGRjZTRmOTY

**Comment by wluberti** [comment]
Thanks for the link, that one works :+1: 
However, I can't seem to find the #nodesharing channel. Is it hidden?

**Comment by devender-yadav** [comment]
@wluberti ,

type  #nodesharing, you will see it

**Comment by rafaelbrizola** [comment]
Thanks! @devender-yadav

**Comment by tawago** [comment]
@rafaelbrizola new join link.
Here's the link to join the IOTA Slack: https://join.slack.com/t/iotatangle/shared_invite/enQtMjgzNDMwNTc2ODg3LTYwNmFjODNhOThjZDA3OGIzZWIxYjFjYWY4YjAzYjg1NDVlMGVkMWE3N2EyODRiY2UyYmI5OWI4ZDU5MjY0NjQ this link will be valid for up to 1000 users and will then need to be reset. If the link expires, please notify a mod.

please, close this since it is not relevant to IRI issues.
