### ISSUE TITLE
Being a part of this great project

### ISSUE THREAD

**Issue by serkanersanli** [iotaledger/iri#385]
Hi I would like to contribute to and be part of this great initiative. How I can assist you as a developer or contributor ?

Thanks
Serkan

**Comment by tawago** [comment]
@serkanersanli  check the IOTA slack.
Here's the link to join the IOTA Slack: https://join.slack.com/t/iotatangle/shared_invite/enQtMjgzNDMwNTc2ODg3LTYwNmFjODNhOThjZDA3OGIzZWIxYjFjYWY4YjAzYjg1NDVlMGVkMWE3N2EyODRiY2UyYmI5OWI4ZDU5MjY0NjQ this link will be valid for up to 1000 users and will then need to be reset. If the link expires, please notify a mod.

please, close this since it is not relevant to IRI issues.

**Comment by jaafonseca** [comment]
The Slack link is no longer valid. Any chance a new link can be generated?

**Comment by serkanersanli** [comment]
Hello,

I was going to solve this item but just saw @jaafonseca 's comment. @tawago would you want to reply ?

**Comment by pconfig** [comment]
Here's the latest:
https://join.slack.com/t/iotatangle/shared_invite/enQtMjkwNzc4OTY0Mjk0LWEzNDA3YTYzN2E1ZWRlNTMzOGQzZWEyMGQxMWI4ZWE1MzZiNzBhNmMzZmRkYTFkNDdhNWI2MWM2OWJmMGYzZjE

It's only valid for 1000 invites so it'll expire again soon.

**Comment by alon-e** [comment]
Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
