### ISSUE TITLE
Contributing for Beginners

### ISSUE THREAD

**Issue by masonbrothers** [iotaledger/iri#388]
Hello! I am a student looking to help with the IOTA project. I don't have a lot of experience volunteering for open source projects, but I was wondering if there is anything I can do to help!

Thank you!

**Comment by tawago** [comment]
@masonbrothers check the IOTA slack. 
Here's the link to join the IOTA Slack: https://join.slack.com/t/iotatangle/shared_invite/enQtMjgzNDMwNTc2ODg3LTYwNmFjODNhOThjZDA3OGIzZWIxYjFjYWY4YjAzYjg1NDVlMGVkMWE3N2EyODRiY2UyYmI5OWI4ZDU5MjY0NjQ this link will be valid for up to 1000 users and will then need to be reset. If the link expires, please notify a mod.

close this since it is not relevant to IRI issues, please.

**Comment by ixuz** [comment]
The invite link is not working properly, I reach the following message upon trying to join iotatangle's slack.
"This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available."

**Comment by publicocean0** [comment]
Hi me too i d like so follow this project.The slack link is no more active

**Comment by ixuz** [comment]
@publicocean0 Here's the link to join the IOTA Slack: https://join.slack.com/t/iotatangle/shared_invite/enQtMjg5MjE5NTMxNDQzLTVkZDU1NDk2NTZjYjUxYzAxZjk0MTY2NWViZWU0ZmIzMmM2ZjNhMzdiZmU4MDhjY2RkMjAwOGUwZmFiNDQzNWE this link will be valid for up to 1000 users and will then need to be reset. If the link expires, please notify a mod.

**Comment by dantasgut** [comment]
I'd like get a invite,  these links shared expired, please, anybody could share a valid invite?

**Comment by mostaruk** [comment]
Valid for 1k users https://join.slack.com/t/iotatangle/shared_invite/enQtMjkyMDEwNTg5NTU5LTExMWUyYTA1MDc0MTU5NThkOGFlODVhOTM0NjM3ZjVhNDcwMjMzZDk4NDNlMzI5OWMyY2MxZDNmMDIwOTE5ZmQ

**Comment by dantasgut** [comment]
Thank you so much mostaruk!

**Comment by mostaruk** [comment]
@dantasgut Your welcome
