### ISSUE TITLE
Where to find neighbors

### ISSUE THREAD

**Issue by chrishamm** [iotaledger/iri#427]
I'd like to use my new root server to provide a full node but I cannot find any neighbors and neither the Slack auto-invite nor the registration on the IOTA forum is working. What is the right way to proceed?

**Comment by Xmio** [comment]
+1

**Comment by GhostTyper** [comment]
You could fully rely on nelson. Or you could use the helloiota forum: https://forum.helloiota.com/

I would also peer with you, if you wish.

**Comment by Citrullin** [comment]
@GhostTyper Nelson is in Beta Beta. Heard about many issues. I would currently use static neighbors. Okay, that's also a huge hussle, because of the upgrades etc. As I understand Nelson also doesn't solve this issue. It just removes the nodes after a time.

If you want to use static neighbors, you can also write a post on helloiota. There are some people also looking for neighbors. I can also add you, if you are on 1.4.1.4 and not on the testnet... I still need to find this fucking neighbor-node which is on the testnet... Yep, the neighbor topic has some issues.

**Comment by chrishamm** [comment]
Thanks to both of you, I've signed up at HelloIOTA and will post a request there as soon as my account has been confirmed.

**Comment by GhostTyper** [comment]
I use nelson on a "productive" (an open wallet server) node with many, many clients and 35-41 neighbours. nelson is configured to add 5-11 neighbours on top of the 30 fix configured neighbours and is (at least here) running stable ("without issues"). So you could really give it a try. (You can see the neighbour-count on this site: https://iota.lukaseder.de/usage.html, it's practically never dropping below 35.)

Prior to version 0.2.4 nelson eventually removed static neighbours, when they were also using nelson, because they would then be treated as nelson node and therefore be evaluated by nelson.

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
