### ISSUE TITLE
--remote-limit-api not working anymore

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#64]
Since 1.1.2.6 its not possible to block the api calls for remote access.

**Comment by project-Shift** [comment]
I cannot reproduce that, it's working just fine on my node
What OS are you using?

Are you using the right command? it's just one dash -remote-limit-api

**Comment by pinpong** [comment]
It was working with the older version of iri. I have nothing changed within the service file.

**Comment by project-Shift** [comment]
sorry, my comment is wrong, it's a double dash

**Comment by project-Shift** [comment]
before the fix, any command that was blocked would also be blocked to local loopback interface
The fix just checks for isLoppback and accepts the call if it is
That's the only difference introduced

**Comment by project-Shift** [comment]
for example, http://walletservice.iota.community:14265 has getNeighbors blocked remotely
but locally I can use it

Could it be that the way you're accessing IRI be taken as local? Are you using any of those old proxy schemes used to get remote access before there was the remote option?

**Comment by project-Shift** [comment]
From what OS are you making the call? can you go into slack and PM the node so I can try?

**Comment by project-Shift** [comment]
So, based on the diagnostics made, there's a possibility that it's a local only problem, because your node sees all API calls coming from the loopback address
Let me know what you find out, ok? I really think the fix applied is an universal solution, but it does stand on the premise that node operators still want to issue any call locally.
If that poses a problem due to the way nodes are exposed remotely, we may have to devise another strategy for remote API calls

**Comment by pinpong** [comment]
Xinetd Service was the problem, after stopping the service the issue is gone.

Thanks.
