### ISSUE TITLE
Tip-Selection freezes when stitching sidetangle to the maintangle

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iri#846]
### Bug description
Tip-Selection/`getTransactionsToApprove` freezes on IRI nodes in the network after a sidetangle gets stitched to the main tangle. Both on IRI 1.4.x and 1.5.x
*-> It's not clear whether all 1.4.x versions tip-sel freeze.*

### Steps To Reproduce
Write a program which connects to a ZMQ feed of any IRI node and let the program up on a new sidetangle tx create a new tx referencing the sidetangle tx and a maintangle tx. (I'm happy to share the exact program if needed; idea was to get the sidetangle confirmed but rather this phenomenon unfortunately happend)

Shown in this picture (Stitching txs = orange; Note that the bigger blow ball structure is the maintangle and the leaner structure the sidetangle):
![image](https://user-images.githubusercontent.com/1385611/42135384-a4eeff56-7d4a-11e8-88e7-455b56a265d5.png)

### Expected behaviour
Confirmation rate should be steady and tip selection shouldn't freeze.

### Actual behavior
**IRI nodes in the network** become unable to execute `getTransactionsToApprove`.
**A clear almost halt in the Tangle network was observed (obviously, because getting tips was impossible).**
Maybe having the sheer amount of txs of the sidetangle suddenly in the tip-sel might cause it to not complete.

A clear suppression of TPS can be observed in following stats (1:30pm-3:10pm):
![image](https://user-images.githubusercontent.com/1385611/42274208-1d12413a-7f8c-11e8-9018-acc4d03f8c2e.png)

Starting the stitching at 4pm resulted in a very abrupt decline of incoming txs:
![image](https://user-images.githubusercontent.com/1385611/42135445-5d49b23a-7d4b-11e8-9c2c-070bb3163d3d.png)

**Comment by rajivshah3** [comment]
I just restarted my node after it went out of sync due to the sidetangle stitching today and it only took a few seconds to get back into sync:

https://pastebin.com/Xh68qE2L

Could the `getTransactionsToApprove` that's being run on the sidetangle consume resources which the transaction validator would otherwise be using?

**Comment by mstx1** [comment]
Ref : `Maybe having the sheer amount of txs of the sidetangle suddenly in the tip-sel might cause it to not complete.`

Perhaps in the getTransactionsToApprove method, IRI can do the follow type of process so it doesn't bombard itself when trying to follow a huge amount of references all at once.

1. `If` the getTransactionsToApprove sees that it will try to map / go through beyond a certain threshold, like say 'beyond 10 transactions/tips'' (arbitrary number, can be adjusted/scaled depending on node specs or in iri settings), `if` it is past this, `then` iri can do the following instead:

 - Check only the the reference specified, and the first say 9 (abitrary) direct linked transactions that it is mapped to initially, and then start and let a new process take over what it was doing, such as Ex: `passiveConsistancyCheckingForOvercapacityOfTransactions()`

This process would casually continue from these first direct linked transactions, to gradually check the whole consistency all the way to the end of where it is mapped from (the whole sidetangle). This function would run in parallel to IRI's normal operations, and do the same thing it normally would, just at a slower pace, throttling itself, rather then letting itself be consumed by a massive number of tx's (as you mentioned). 

 This function would be in no rush to finish all the links that this new tx has referenced branching off to a whole side-tangle. Once it completes, it basically has now checked the whole side tangle fully, and all other neighboring nodes can also perform a passive absorbing of this very high volume of txs that it knows nothing about, all at thier own pace, passively.

It would only need to enact this new type of passive process in this case where it notices itself trying to check so many things in a certain short time period, then stop itself from continuing and throw itself into this passive process instead.

This original method can detect when it needs to launch a passive passive process in parallel to it's normal operations, with a counter, and a timer. IRI can check how many branches an initial tip is leading off to, and how fast it is going. If it notices it is going down a vortex of txs (ie: it's on a sidetangle), throw the passive process, and let it gradually check it all, at it's own pace.

**Comment by iota-cm** [comment]
Another clear explanation thanks to frha on discord:

There is a sidetangle growing because a guy is constantly publsihing valid transactions confirming two of his own previous ones. He also makes sure that some tx'es is confirmed twice so that the number of tips in his 'sidetangle' is not reduced but stays appx the same all the time..  Not an complex task to do.

Then the random-walk is working with the tx'es confirmed by COO and the 'normal' IRI-implementations only select tips from this part of the tangle...

Then someone (maybe the sidetangle-dude himself) starts a separate line of (also valid) transactions that selects one of the last tx'es in the sidetangle together with the milestones from COO as the two tx'es to be confirmed. This also works fine - a good week ago I made those myself, and at that time the sidetangle was 'short enough' to actually be confirmed, so my 'stitching' actually lead to the sidetangle-tx'es getting confirmed.
Today the sidetangle-tx'es goes so far back before being confirmed that it's virtually (not theroetically) impossible to get them confirmed, but even so - they are valid, and the random-walk does go into those, and then - since it's so long way back to confirmations - the threads seems to hang and makes the node out of sync because it uses all it's resources to find the confirmation-path and don't have time to follow up on incoming tx'es and misses milestones etc...

**Comment by Fumlop** [comment]
I think the traversedTail size has to be limited in WalkAlpha.java on the do while.
No clue what for problem this causes, but in the moment the sidechain joins this code needs to much time.

https://github.com/Fumlop/iri/blob/dev/src/main/java/com/iota/iri/service/tipselection/impl/WalkerAlpha.java

```
  @Override
    public Hash walk(Hash entryPoint, UnIterableMap<HashId, Integer> ratings, WalkValidator walkValidator) throws Exception {
        if (!walkValidator.isValid(entryPoint)) {
            throw new IllegalStateException("entry point failed consistency check: " + entryPoint.toString());
        }
        
        Optional<Hash> nextStep;
        Deque<Hash> traversedTails = new LinkedList<>();
        traversedTails.add(entryPoint);

        //Walk
        do {
            nextStep = selectApprover(traversedTails.getLast(), ratings, walkValidator);
            nextStep.ifPresent(traversedTails::add);
            
            if (traversedTails.size()>= maxTraversedTailSize) break;
            
        } while (nextStep.isPresent());
        
        log.debug("{} tails traversed to find tip", traversedTails.size());
        messageQ.publish("mctn %d", traversedTails.size());

        return traversedTails.getLast();
    }

```

**Comment by Fumlop** [comment]
Think there has to be a limit on the traversedTail size, but the consequence could be a easier "respend" on another address.


```
private final long maxTraversedTailSize = 10000;

  @Override
    public Hash walk(Hash entryPoint, UnIterableMap<HashId, Integer> ratings, WalkValidator walkValidator) throws Exception {
        if (!walkValidator.isValid(entryPoint)) {
            throw new IllegalStateException("entry point failed consistency check: " + entryPoint.toString());
        }
        
        Optional<Hash> nextStep;
        Deque<Hash> traversedTails = new LinkedList<>();
        traversedTails.add(entryPoint);

        //Walk
        do {
            nextStep = selectApprover(traversedTails.getLast(), ratings, walkValidator);
            nextStep.ifPresent(traversedTails::add);
            
            if (traversedTails.size()>= maxTraversedTailSize) break;
            
        } while (nextStep.isPresent());
        
        log.debug("{} tails traversed to find tip", traversedTails.size());
        messageQ.publish("mctn %d", traversedTails.size());

        return traversedTails.getLast();
}
```

**Comment by ben-75** [comment]
Is it possible that the freeze is caused by the TransactionValidator.checkSolidity() method (called from TipsManager.randomWalk() ) ?

When looking at the code (as far as I understand), when the random walk move to a new site, it will check the solidity of this site.
As long as the side tangle wasn't connected, it was impossible to reach one site of the side-tangle.

Now that they are connected, the walk may reach a stiching-transaction and start the solidity check... and analyze one-by-one almost all transactions of the side-tangle to finally ends on the root of the side tangle, which have no parent.
Problem is that the history of transactions in the side tangle is huge and none of them is solid (because the branch and trunk transactions of the first transaction in the side tangle don't exists)

**Comment by mstx1** [comment]
@GalRogozinski 

But if this 1 main background process is launched, it could be just that...1 background process that checks things in a controlled + casual manner, since the first (1.) conditions stops it from going crazy and lets the passive process handle these exceptions.

'1 instance of the passive process' is only running at a time allocating whatever resources appropriate, and that 1 process only continues the road it started on from it's initial reference in series, until it finishes the whole mapping.

And if there is a totally new query to the first method, that also does not satisfy the (1.) and 'wants to' throw another instance of the passive process, the parameters of the initial call can be queued into an array. Once the 1 passive process actually completes wherever it had to go in it's own controlled / casual manner. It can check it's: `starting ref calls that needed myself`' array (which could be just the string parameters essentially of the actual initial call that didn't pass the (1.) part). 

If there is an item in that ''next in line'' array for the passive process after that 1 instance passive checker completed wherever it had to amp out in line, it can call the first normal method with the next item's params, just to check if it still ''requires the passive process'', if so-> it engages the passive process once again for the 'next in line' item, so there is only ever 1 main background instance of this process running, to take care of these exceptions.

Why would it not complete ?
