### ISSUE TITLE
Broken Dockerfile: PPA removed oracle-java8-installer=8u171-1

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iri#877]
### Bug description
Dockerfile does not build docker image anymore, PPA repository removed oracle-java8-installer=8u171-1

### Steps To Reproduce
1. docker build . 

### Expected behaviour
apt gets PPA oracle-java8-installer version.

### Actual behavior
Removed on the PPA.

### Errors
```
E: Version '8u171-1~webupd8~0' for 'oracle-java8-installer' was not found
```

### Am I planning to do it myself with a PR?
Yes.

**Comment by geminoz** [comment]
We will be moving to self-providing specific java versions via specific docker containers

**Comment by geminoz** [comment]
The PPA repo maintainers seem to keep only the latest version, for whatever reason

**Comment by nuriel77** [comment]
Oracle java change version and it takes ppa a couple of days to catch up and update.
Actually, this dependency on Oracle is quite annoying to maintain.
Question: why use Oracle Java in the first place? Is there any specific reason why to choose it over openjdk?

**Comment by GalRogozinski** [comment]
According to @alon-e IRI is more stable on OracleJDK.
@geminoz notify me when the PR is ready.

**Comment by geminoz** [comment]
Nuriel: the actual problem is due to the PPA maintainer not keeping previous versions of the oracle-java8 deb packages. We have been using 171 for a while, now they bumped it to 181, but the 171 is no longer in their repos. I'm sure there is a good reason behind it, but this means we need to have another approach.

Gal: we have been using oracle-java8 for a while now. I suggest we stick to it and eventually track down a switch over to OracleJDK in another GitHub issue. As far as I am aware, I always had a better experience with the Oracle version of Java when running IRI and I remember previous indications to favour the Oracle one instead of the Open one.

**Comment by geminoz** [comment]
How to move forward? Two options:
1) we change the Dockerfile not to reference any specific Oracle-Java8 version, which means the PPA maintainers can bump to a newest release at any time without us knowing about it. I don't like that

2) we change the Dockerfile to use pre-built (by the IF, stored in the iotaledger docker hub repo) docker containers with a specific version of Oracle-Java8, instead of using docker build stages and download the Oracle-Java8 package from the PPA on-the-fly each time.

Option 2 is my choice of preference. It adds a little more complexity and overhead - we have one more docker container to maintain - but at least we will be 100% sure of what we compile Maven and IRI against.

I ask the community and anyone interested for their opinion. If there is a substantial agreement on how to proceed, I will make it happen

@nuriel77 @ahab94 @karimodm @sadjy

**Comment by nuriel77** [comment]
@geminoz option 2 sounds 👍
