### ISSUE TITLE
Test parallel calls to GTTA 

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#973]
### Description
Test calling GTTA on a single node in parallel and see how long it takes for the individual calls to return a response. We should enable parallelism (by disabling synchronization, as done here: #1245 ) on GTTA and see how it performs compared to a normal node.

**This test already exists in the Tangle tools repo already, where we have jMeter spammer. So this just needs some minor change-up:** https://github.com/iotaledger/tangle-tools/tree/master/Jmeter-Spammer 

Are we threadsafe?
Are milestones still being updated as the calls come in?
Should we only allow parallelism up to a certain amount of active requests? So the node doesn't get DOSed. 

**This being the first nightly test, part of the scope is establishing with @geminoz how we run and deploy these tests on Spamnet (or other network).**

### Motivation
Figure out if we need to invest in making changes to IRI to support better parallelization, CW caching or tip caching in the future to accommodate faster responses to GTTA that do not overload the nodes. 

### Requirements
- [ ] Use jMeter to simulate different workers. 
- [ ] Make a 1000 calls with the same depth at the same time and log the time it takes to response to all of them - with synchronizations. 
- [ ] Make a 1000 calls with the same depth at the same time and log the time it takes to response to all of them - without synchronizations.
- Run jMeter via the command line. 
- The test is also run against manually against the #1245 PR.

### Open Questions (optional)
- [ ] Where do we upload the results?

We can change the numbers later on to establish where is a good cut-off for parallel active requests.

**Comment by jakubcech** [comment]
Hi @marktwtn, happy if you take a look at it and post your results here. Please let me know if anything's unclear with regards to the description. :) 👍

**Comment by marktwtn** [comment]
I was wondering about the question.
```
Are milestones still being updated as the calls come in?
```
Which milestone is preferred in the question?
`latestMilestone`, `latestSolidSubtangleMilestoneIndex` or both?

**Comment by marktwtn** [comment]
The experiment result of making a 1000 calls with the same depth at the same time and logging the time it takes to response to all of them:

The black dots in the charts are the response time.

IRI 1.5.3 - with synchronization
![gtta parallel test on testnet - 1 5 3](https://user-images.githubusercontent.com/6748200/50194636-bfc69e80-0376-11e9-812c-27c423e8d378.png)

Maximum response time: 23731 ms
Throughput: 2,373.699 / minute

IRI 1.5.5 - without synchronization
![gtta parallel test on testnet - no sync](https://user-images.githubusercontent.com/6748200/50194641-c228f880-0376-11e9-8182-afba25668173.png)

Maximum response time: 3694 ms
Throughput: 15,011.258 / minute

The without synchronization version of IRI has lower response time and higher throughput.

---

> Are we threadsafe?

Yes.
The GTTA execution has Java `readWriteLock` to protect the data.
It uses read lock since most of the execution are related to read.
The read lock allows multiple GTTA threads to read the data at the same time.

> Are milestones still being updated as the calls come in?

Yes.
The update code uses the corresponding write lock, which is the opposite of the GTTA request read lock.
However, the update only happens around every 30 secs to 1min.
Hence even under the scenario of intense GTTA requests coming, the milestones are updated normally.

**Comment by jakubcech** [comment]
Thank you so much for the investigation @marktwtn !

**Comment by DyrellC** [comment]
I am going to also test logging the results from the command line execution and using scripts to analyse them, as per @GalRogozinski suggestion.

**Comment by GalRogozinski** [comment]
Hey @DyrellC 
In addition to the tests that you have created can you create a test that has only a few users calling GTTA simultaneously in a loop? Let say one test with 5 users calling GTTA simulataneously and 10 users. 
Play with the length of the loop to see how it affects the results. If a longer loop doesn't change the results much opt to create a final version with a shorter loop.

In the end do a PR to all your tests to this location: https://github.com/iotaledger/iri-regression-tests/tree/master/Nightly-Tests/Jmeter-Tests
